<?php $title = 'Error'; ?>
<?php require('head.phtml'); ?>
        <h2>An error occured!</h2>
        <p>
          Something wrong happened while running your code.
          The following error was encountered:
        </p>
        <pre><?php echo $vars->exception->getMessage(); ?></pre>

        <p>Trace:</p>
        <pre><?php echo $this->printTrace($vars->exception); ?></pre>
<?php require('foot.phtml'); ?>
