<?php $title = "Page not found"; ?>
<?php require('head.phtml'); ?>
        <h2>We couldn't find what you look for.</h2>
        <p>
            <?php if($vars->exception->getMessage()): ?>
                <?php echo $vars->exception->getMessage(); ?>
            <?php else: ?>
                The resource you asked for couldn't be found.
            <?php endif; ?>
        </p>
        <p>Prefix:</p>
        <pre>'<?php echo $this->server->getPrefix(); ?>'</pre>
        <p>Request:</p>
        <pre>'<?php echo $this->server->getRoute(); ?>'</pre>
        <p>Routes:</p>
        <table>
            <tr><th>Route</th><th>App[call]</th></tr>
            <?php foreach($vars->exception->getRoutes() as $route => $target): ?>
                <tr>
                    <td><code>'<?php echo $route;?>'</code></td>
                    <td><code><?php echo $target->getApp();?>[<?php echo $target->getCall();?>]</code></td>
                </tr>
            <?php endforeach; ?>
        </table>
<?php require('foot.phtml'); ?>
