<!DOCTYPE html>
<html>
  <head>
    <title>Assegai - Error</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style type="text/css">
html {
    font-family: Ubuntu,Helvetica,Cambria,Arial,sans-serif;
}
body {
    background-color: #ffffff;
    padding: 0;
    margin: 0;
}
#pagewrapper {
    width: 960px;
    margin: 0 auto;
    background-color: #fff;
    box-shadow: 0 0 10px 0 #000;
}
#content {
    padding: 0 1em 1em;
}
header {
    background-color: #553322;
    color: #fff;
    height: 100px;
}
header h1 {
    float: left;
    font-size: 40px;
    margin: 25px 0 0 25px;
    padding: 0;
}
header h3 {
    float: left;
    font-size: 15px;
    margin: 48px 0 0 15px;
    padding: 0;
}
footer {
    background-color: #996644;
    text-align: center;
    padding: 0.2em 0;
}
footer a {
    color: #fff;
}
pre {
    background-color: #cc9966;
    border-radius: 10px;
    padding: 1em;
}
    </style>
  </head>
  <body>
    <div id="pagewrapper">
      <header>
        <h1>Assegai</h1>
        <h3>The easy framework</h3>
      </header>

      <div id="content">
        <h2>An error occured!</h2>
        <p>
          Something wrong happened while running your code.
          The following error was encountered:
        </p>
        <pre><?=$e->getMessage()?></pre>

        <p>Trace:</p>
        <pre><?=$printtrace($e)?></pre>
      </div>

      <footer>
        <p>
          Powered by <a href="http://assegai.etenil.net">Assegai</a>.
        </p>
      </footer>
    </div>
  </body>
</html>